# @Author: Othmane N.
# @Date:   2024-03-14 18:16H
# 🚨 GTHUB SECRETS REQUIRED: None

name: Main Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Compile SCSS
      run: npm run compile-scss

    - name: Format CSS
      run: npm run format-css

    - name: Relase new version
      run: npm run release

    - name: Add changes
      run: git add .

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[ci: main-release.yml]"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}